name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    paths:
      - "resources/js/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "vite.config.ts"
env:
  LARAVEL_BYPASS_ENV_CHECK: 1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093
        with:
          version: 11
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm ci
      - run: pnpm run build --if-present
      - run: pnpm test
